/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Farg-
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JLabel();
        btnHospetaje = new javax.swing.JButton();
        btnTransporte = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/CERRAR-SESION.png"))); // NOI18N
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        btnHospetaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHospetaje.setText("Hospedaje");
        btnHospetaje.setToolTipText("");
        btnHospetaje.setBorder(null);
        btnHospetaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospetajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospetaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 110, 40));

        btnTransporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTransporte.setText("Transporte");
        btnTransporte.setToolTipText("");
        btnTransporte.setBorder(null);
        btnTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 110, 40));

        btnViajes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViajes.setText("Viajes");
        btnViajes.setToolTipText("");
        btnViajes.setBorder(null);
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/HOME.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        FlightWindow v1 = new FlightWindow();
        v1.show();
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransporteActionPerformed
        TransportWindow v3 = new TransportWindow();
        v3.show();
    }//GEN-LAST:event_btnTransporteActionPerformed

    private void btnHospetajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospetajeActionPerformed
        LodgingWindow v2 = new LodgingWindow();
        v2.show();
    }//GEN-LAST:event_btnHospetajeActionPerformed

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestro sistema. Vuelva Pronto.");
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JButton btnHospetaje;
    private javax.swing.JButton btnTransporte;
    private javax.swing.JButton btnViajes;
    // End of variables declaration//GEN-END:variables
}
