package GUI;

import DataBaseControl.CredentialsDB;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBadcreds = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();
        btnUserLogin = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBadcreds.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtBadcreds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtBadcreds, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 300, 20));

        txtUserEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        getContentPane().add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 370, 60));

        txtUserPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 370, 60));

        btnAdminLogin.setText("Administrador");
        btnAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminLoginMousePressed(evt);
            }
        });
        getContentPane().add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 110, 30));

        btnUserLogin.setText("Ingresar");
        btnUserLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserLoginMousePressed(evt);
            }
        });
        getContentPane().add(btnUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 100, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/INICIO-SESION.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserLoginMousePressed
        CredentialsDB dbConection;
        String dbPassword;
        
        String userEmail = txtUserEmail.getText();
        String userPassword = String.valueOf(txtUserPassword.getPassword());

        try{
            dbConection = new CredentialsDB();
            dbPassword = dbConection.getUserPassword(userEmail, CredentialsDB.usuarios);
            
            if (dbPassword.equals(userPassword)){
                
            }
            else{
                
            }
        }
        catch (Exception e){}
    }//GEN-LAST:event_btnUserLoginMousePressed

    private void btnAdminLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLoginMousePressed
        CredentialsDB dbConection;
        String dbPassword;
        
        String userEmail = txtUserEmail.getText();
        String userPassword = String.valueOf(txtUserPassword.getPassword());

        try{
            dbConection = new CredentialsDB();
            dbPassword = dbConection.getUserPassword(userEmail, CredentialsDB.administradores);
            
            if (dbPassword.equals(userPassword)){
                
            }
            else{
                txtBadcreds.setText("txtBadcreds");
            }
        }
        catch (Exception e){}
    }//GEN-LAST:event_btnAdminLoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JLabel txtBadcreds;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
