/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminSystem;

/**
 *
 * @author Farg-
 */
public class AdministrationSystem extends javax.swing.JFrame {

    /**
     * Creates new form AdministrationSystem
     */
    public AdministrationSystem() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDBprovedores = new javax.swing.JButton();
        btnDBempleados = new javax.swing.JButton();
        btnDBusuarios = new javax.swing.JButton();
        btnDBproductos = new javax.swing.JButton();
        btnDBviajes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDBprovedores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBprovedores.setText("DB Provedor");
        btnDBprovedores.setToolTipText("");
        btnDBprovedores.setBorder(null);
        btnDBprovedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBprovedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBprovedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 120, 40));

        btnDBempleados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBempleados.setText("DB Empleados");
        btnDBempleados.setToolTipText("");
        btnDBempleados.setBorder(null);
        btnDBempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBempleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 120, 40));

        btnDBusuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBusuarios.setText("DB Usuarios");
        btnDBusuarios.setToolTipText("");
        btnDBusuarios.setBorder(null);
        btnDBusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBusuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 110, 40));

        btnDBproductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBproductos.setText("DB Productos");
        btnDBproductos.setToolTipText("");
        btnDBproductos.setBorder(null);
        btnDBproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBproductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 130, 40));

        btnDBviajes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDBviajes.setText("DB Viajes");
        btnDBviajes.setToolTipText("");
        btnDBviajes.setBorder(null);
        btnDBviajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBviajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDBviajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 110, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administracion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DISEÑOCOMPLETO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDBviajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBviajesActionPerformed
        DBtrips v1 = new DBtrips();
        v1.show();
    }//GEN-LAST:event_btnDBviajesActionPerformed

    private void btnDBproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBproductosActionPerformed
        DBproducts v2 = new DBproducts();
        v2.show();
    }//GEN-LAST:event_btnDBproductosActionPerformed

    private void btnDBusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBusuariosActionPerformed
        DBusers v3 = new DBusers();
        v3.show();
    }//GEN-LAST:event_btnDBusuariosActionPerformed

    private void btnDBempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBempleadosActionPerformed
        DBemployees v4 = new DBemployees();
        v4.show();
    }//GEN-LAST:event_btnDBempleadosActionPerformed

    private void btnDBprovedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBprovedoresActionPerformed
        DBproviders v5 = new DBproviders();
        v5.show();
    }//GEN-LAST:event_btnDBprovedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDBempleados;
    private javax.swing.JButton btnDBproductos;
    private javax.swing.JButton btnDBprovedores;
    private javax.swing.JButton btnDBusuarios;
    private javax.swing.JButton btnDBviajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
